# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0biface.proto\x12\x05proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x18\n\x0b\x41\x64\x64Response\x12\t\n\x01n\x18\x01 \x01(\x05\"\x17\n\nSumRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"\x18\n\x0bSumResponse\x12\t\n\x01n\x18\x01 \x01(\x05\"&\n\x0cRangeRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\x0b\n\x03len\x18\x02 \x01(\x05\"\x1a\n\rRangeResponse\x12\t\n\x01n\x18\x01 \x01(\x05\"#\n\x0b\x45\x63hoRequest\x12\t\n\x01n\x18\x01 \x01(\x05\x12\t\n\x01s\x18\x02 \x01(\t\"$\n\x0c\x45\x63hoResponse\x12\t\n\x01n\x18\x01 \x01(\x05\x12\t\n\x01s\x18\x02 \x01(\t2g\n\x03\x41\x64\x64\x12.\n\x03\x41\x64\x64\x12\x11.proto.AddRequest\x1a\x12.proto.AddResponse\"\x00\x12\x30\n\x03Sum\x12\x11.proto.SumRequest\x1a\x12.proto.SumResponse\"\x00(\x01\x32?\n\x05Range\x12\x36\n\x05Range\x12\x13.proto.RangeRequest\x1a\x14.proto.RangeResponse\"\x00\x30\x01\x32=\n\x04\x45\x63ho\x12\x35\n\x04\x45\x63ho\x12\x12.proto.EchoRequest\x1a\x13.proto.EchoResponse\"\x00(\x01\x30\x01\x42\x04Z\x02./b\x06proto3')



_ADDREQUEST = DESCRIPTOR.message_types_by_name['AddRequest']
_ADDRESPONSE = DESCRIPTOR.message_types_by_name['AddResponse']
_SUMREQUEST = DESCRIPTOR.message_types_by_name['SumRequest']
_SUMRESPONSE = DESCRIPTOR.message_types_by_name['SumResponse']
_RANGEREQUEST = DESCRIPTOR.message_types_by_name['RangeRequest']
_RANGERESPONSE = DESCRIPTOR.message_types_by_name['RangeResponse']
_ECHOREQUEST = DESCRIPTOR.message_types_by_name['EchoRequest']
_ECHORESPONSE = DESCRIPTOR.message_types_by_name['EchoResponse']
AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESPONSE,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.AddResponse)
  })
_sym_db.RegisterMessage(AddResponse)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMREQUEST,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.SumRequest)
  })
_sym_db.RegisterMessage(SumRequest)

SumResponse = _reflection.GeneratedProtocolMessageType('SumResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMRESPONSE,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.SumResponse)
  })
_sym_db.RegisterMessage(SumResponse)

RangeRequest = _reflection.GeneratedProtocolMessageType('RangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANGEREQUEST,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.RangeRequest)
  })
_sym_db.RegisterMessage(RangeRequest)

RangeResponse = _reflection.GeneratedProtocolMessageType('RangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _RANGERESPONSE,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.RangeResponse)
  })
_sym_db.RegisterMessage(RangeResponse)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'iface_pb2'
  # @@protoc_insertion_point(class_scope:proto.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

_ADD = DESCRIPTOR.services_by_name['Add']
_RANGE = DESCRIPTOR.services_by_name['Range']
_ECHO = DESCRIPTOR.services_by_name['Echo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _ADDREQUEST._serialized_start=22
  _ADDREQUEST._serialized_end=56
  _ADDRESPONSE._serialized_start=58
  _ADDRESPONSE._serialized_end=82
  _SUMREQUEST._serialized_start=84
  _SUMREQUEST._serialized_end=107
  _SUMRESPONSE._serialized_start=109
  _SUMRESPONSE._serialized_end=133
  _RANGEREQUEST._serialized_start=135
  _RANGEREQUEST._serialized_end=173
  _RANGERESPONSE._serialized_start=175
  _RANGERESPONSE._serialized_end=201
  _ECHOREQUEST._serialized_start=203
  _ECHOREQUEST._serialized_end=238
  _ECHORESPONSE._serialized_start=240
  _ECHORESPONSE._serialized_end=276
  _ADD._serialized_start=278
  _ADD._serialized_end=381
  _RANGE._serialized_start=383
  _RANGE._serialized_end=446
  _ECHO._serialized_start=448
  _ECHO._serialized_end=509
# @@protoc_insertion_point(module_scope)
